# ------------------------------------------------------------------------------
# Production Environment
# ------------------------------------------------------------------------------
port: 1337

# log:
  # level: debug

# ------------------------------------------------------------------------------
# Plugins
# ------------------------------------------------------------------------------
# plugins:
  # - sailor-module-user

# ------------------------------------------------------------------------------
# Core
# ------------------------------------------------------------------------------
# paths:
  # hooks: 'path_to_hooks'
